Code rafactored
eugeneJadeszko/CouchBaseRabbit pull request #22
Opened 2017-07-19 07:40 UTC by vladiskp

Code refactored. Now RabbitMQ listener get Subscriber with inner model CallRecord in json format.

2017-07-19 08:25 UTC, vitaliisergey commented on src/by/intexsoft/billing/service/impl/QueueListenerImpl.java
> +     * Convert input JSON string into Subscriber object
должен быть link на Subscriber

2017-07-19 08:25 UTC, vitaliisergey commented on src/by/intexsoft/billing/service/impl/QueueWriterImpl.java
> +	private String convertObjectToJson(Subscriber subscriber) {
просто convert назовите

2017-07-19 08:29 UTC, vitaliisergey requested changes

2017-07-19 08:29 UTC, vitaliisergey commented on src/by/intexsoft/billing/service/impl/QueueWriterImpl.java
> +		String result = "";
Может тут сразу без переменной

2017-07-19 08:29 UTC, vitaliisergey commented on src/by/intexsoft/billing/service/impl/SubscriberBuilderImpl.java
> +     * Build unique Subscriber object
нужен link

2017-07-19 08:29 UTC, vitaliisergey commented on src/by/intexsoft/billing/model/Subscriber.java
> +    public Subscriber(int id, String firstName, String secondName, int age, CallRecord callRecord) {
Где документация

2017-07-19 08:29 UTC, vitaliisergey commented on src/by/intexsoft/billing/model/Subscriber.java
>      public Subscriber(){}
Документация

2017-07-19 08:29 UTC, vitaliisergey commented on src/by/intexsoft/billing/service/impl/SubscriberBuilderImpl.java
> +     * @return unique Subscriber object
Link

2017-07-19 09:37 UTC, vitaliisergey approved these changes

2017-07-19 09:39 UTC, eugeneJadeszko approved these changes

2017-07-19 09:41 UTC, vitaliisergey requested changes

2017-07-19 09:41 UTC, vitaliisergey commented on src/by/intexsoft/billing/model/Subscriber.java
>      public int id;
А тут? Тут же public

2017-07-19 10:05 UTC, eugeneJadeszko commented on src/by/intexsoft/billing/model/CallRecord.java
> -     * @param id unique id
Если мы комментим field, то оставлять почти те же комментарии над конструктором стоит?

2017-07-20 08:05 UTC, vitaliisergey submitted a review, later dismissed

2017-07-20 08:07 UTC, merged